project:
  type: website

website:
  title: "Chris Donovan"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    tools:
      - icon: github
        href: https://github.com/chrisdonovan307/site
  page-footer:
    left: |
      <p>
        Licensed under
        <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">Creative Commons BY-NC-SA 4.0</a>
      </p>
  back-to-top-navigation: true

format:
  html:
    theme: 
      - cosmo
      - assets/styling/styles.scss
    toc: true
    toc-depth: 4
    smooth-scroll: true
    # grid:
      # body-width: 400px
      # sidebar-width: 100px


