project:
  type: website

website:
  title: "Chris Donovan"
  page-navigation: true
  page-footer:
    left: |
      <p>
        Licensed under
        <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">Creative Commons BY-NC-SA 4.0</a>
      </p>
    right: |
      <p>Made with <a href="https://quarto.org" target="_blank">Quarto</a></p>
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
    tools:
      - icon: github
        menu: 
          - text: Personal
            href: https://github.com/chrisdonovan307
          - text: FSRI
            href: https://github.com/Food-Systems-Research-Institute
  back-to-top-navigation: true

format:
  html:
    theme: 
      - cosmo
      - assets/styling/custom.scss
    css: assets/styling/styles.css
    toc: true
    toc-depth: 4
    smooth-scroll: true
    # grid:
      # body-width: 400px
      # sidebar-width: 100px
